name: Docker Build

on:
  workflow_call:
    inputs:
      BUILD_TARGET:
        type: string
        required: false
        default: release
      NODE_ENV:
        type: string
        required: false
        default: production
      SERVER_PUSH:
        type: string
        required: false
        default: production
    secrets:
      NPM_TOKEN:
        required: false
      FORTAWESOME_TOKEN:
        required: false

jobs:
  build:
    name: ${{ inputs.BUILD_TARGET }} ${{ inputs.NODE_ENV }} ${{ inputs.SERVER_PUSH }}
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@master

      - name: start containers
        run: docker compose -f "docker-compose.yml" up --build --abort-on-container-exit
        env:
          BUILD_TARGET: ${{ inputs.BUILD_TARGET }}
          NODE_ENV: ${{ inputs.NODE_ENV }}
          SERVER_PUSH: ${{ inputs.SERVER_PUSH }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          FORTAWESOME_TOKEN: ${{ secrets.FORTAWESOME_TOKEN }}
        continue-on-error: false

      - name: stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down