name: Docker Publish

on:
  workflow_call:
    secrets:
      npm_token:
        required: true

jobs:
  build-dev:
    name: Build Dev
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Start containers
        run: docker compose -f "docker-compose.yml" up -d --build
        env:
          docker_target: test

      - name: Install node
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down