name: Docker Publish

on:
  workflow_call:
    secrets:
      docker_username:
        required: true
      docker_token:
        required: true
      docker_tag:
        required: true
      gh_token:
        required: true

jobs:
  publish:
    name: Docker Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@master

      - name: Setup QEMU
        uses: docker/setup-qemu-action@master

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: DockerHub Login
        uses: docker/login-action@master
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.docker_tag }}
          secrets: |
            git_auth_token=${{ secrets.gh_token }}