name: Build and Tests

on:
  workflow_call:
    inputs:
      reponame:
        required: true
        type: string

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      reponame: ${{ inputs.reponame }}