name: Build and Tests

on:
  workflow_call:
    inputs:
      reponame:
        required: true
        type: string

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: cosmicverse/workflows/.github/workflows/run-tests.yml@main
        with:
          reponame: ${{ inputs.reponame }}