name: GPR Publish Package

on:
  workflow_call:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm i
      - run: npm run package:build
        continue-on-error: false
      - run: npm run package:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GPR_TOKEN}}
          TOKEN: ${{secrets.GPR_TOKEN}}