name: Library Publish

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    name: build library
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: checkout actions
        uses: actions/checkout@v4
#
#      - name: setup npm
#        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: cache packages
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ false == steps.cache-npm.outputs.cache-hit }}
        name: list packages
        continue-on-error: true
        run: npm list

      - name: install packages
        run: npm ci
#        env:
#          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build library
        run: npm run release
        continue-on-error: false

      - name: gpr publish
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 20.x
          registry-url: https://npm.pkg.github.com

      - name: publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: npm publish
#        uses: actions/setup-node@v4
#        with:
#          always-auth: true
#          node-version: 20.x
#          registry-url: https://registry.npmjs.org
#
#      - name: publish package
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}