name: Library Development

on:
  workflow_call:
    inputs:
      BUILD_TARGET:
        type: string
        required: false
        default: release
      NODE_ENV:
        type: string
        required: false
        default: production
      VITE_MODE:
        type: string
        required: false
        default: production
    secrets:
      NPM_TOKEN:
        required: false
      FORTAWESOME_TOKEN:
        required: false

jobs:
  build:
    name: ${{ inputs.BUILD_TARGET }} ${{ inputs.NODE_ENV }} ${{ inputs.VITE_MODE }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v3

      - name: setup npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: cache packages
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ false == steps.cache-npm.outputs.cache-hit }}
        name: list packages
        continue-on-error: true
        run: npm list

      - name: install packages
        run: npm ci

      - name: build
        run: npm run ${{ inputs.BUILD_TARGET }}
        env:
          BUILD_TARGET: ${{ inputs.BUILD_TARGET }}
          NODE_ENV: ${{ inputs.NODE_ENV }}
          VITE_MODE: ${{ inputs.VITE_MODE }}
        continue-on-error: false
