name: Lint Code

on:
  workflow_call:

jobs:
  lint:
    name: lint code
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: cache packages
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-lint-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ false == steps.cache-npm.outputs.cache-hit }}
        name: list packages
        continue-on-error: true
        run: npm list

      - name: install packages
        run: npm ci

      - name: execute lint
        run: npm run lint
        continue-on-error: false
