name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '18.x'

      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@master
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-lint-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ false == steps.cache-npm.outputs.cache-hit }}
        name: List Node Modules State
        continue-on-error: true
        run: npm list

      - name: Install Dependencies
        run: npm i

      - name: Execute Linter
        run: npm run lint:exec
        continue-on-error: false
