name: Lint

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: false
      FORTAWESOME_TOKEN:
        required: false

jobs:
  lint:
    name: code
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v3

      - name: setup npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FORTAWESOME_TOKEN }}" >> .npmrc

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: cache packages
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ false == steps.cache-npm.outputs.cache-hit }}
        name: list packages
        continue-on-error: true
        run: npm list

      - name: install packages
        run: npm ci

      - name: lint
        run: npm run lint
        continue-on-error: false
