name: Package Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm run package:build
      - run: npm package:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}