name: Package Publish

on:
  workflow_call:

jobs:
  publish:
    name: Package Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-release-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ false == steps.cache-npm.outputs.cache-hit }}
        name: List Node Modules State
        continue-on-error: true
        run: npm list

      - name: Install Dependencies
        run: npm ci

      - name: Build Release
        run: npm run release:build
        continue-on-error: false

      - name: NPM Publish
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Publish Package
        run: npm package:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: false

      - name: GitHub Package Repository Publish
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish Package
        run: npm run package:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false