name: Package Publish

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    name: Package Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3

      - name: Setup .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.npm_token }}" > .npmrc

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-release-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ false == steps.cache-npm.outputs.cache-hit }}
        name: List Node Modules State
        continue-on-error: true
        run: npm list

      - name: Install Dependencies
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: Build Release
        run: npm run build
        continue-on-error: false

      - name: NPM Publish
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 18.x
          registry-url: https://registry.npmjs.org

      - name: Package Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: GPR Publish
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com

      - name: Package Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}