name: Publish Package

on:
  push:
    branches: [ main ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: ./.github/workflows/lint
      - uses: ./.github/workflows/prod-build
      - uses: ./.github/workflows/test
      - run: npm run package:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: publish-npm
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: ./.github/workflows/lint
      - uses: ./.github/workflows/prod-build
      - uses: ./.github/workflows/test
        with:
          registry-url: https://npm.pkg.github.com/
      - run: npm run package:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR_TOKEN}}
